//竖向柱状
var myChart_zhu_1 = new FusionCharts("Column3D.swf?PBarLoadingText=Loading&XMLLoadingText=Loading&ParsingDataText=Loading", "myChartId_zhu_1", "660", "250", "0", "0");
								    myChart_zhu_1.addParam('wmode','transparent');
                                    myChart_zhu_1.setDataXML("<chart baseFontSize='12' baseFontColor='888888' outCnvBaseFontColor='999999' outCnvBaseFontSize='12' numberSuffix='%25' showAboutMenuItem='0' decimals='2' yAxisMaxValue='100' palette='2' enableRotation='1' canvasBgColor='ffffff' canvasBgAlpha='40' canvasBgDepth='3' canvasBaseColor='ffffff' divLineColor='d8d8d8' numDivLines='4' bgAlpha='0' logoURL='http://www.sinaimg.cn/dy/deco/2009/0903/survey/wmark_column3_1.png' logoPosition='TR' divLineColor='d8d8d8' canvasPadding='8' chartLeftMargin='0' chartRightMargin='5' chartTopMargin='5' chartBottomMargin='0' maxColWidth='70' showValues='1'><styles><definition><style name='myToolTip' type='font' size='12' color='666666' /></definition><application><apply toObject='ToolTip' styles='myToolTip' /></application></styles><set label='1级' value='55.8' toolText='1级 (55.8%)' /><set label='2级' value='25.3' toolText='2级 (25.3%)' /><set label='3级' value='18.9' toolText='3级 (18.9%)' /><set label='4级' value='80.9' toolText='4级 (80.9%)' /><set label='5级' value='18.9' toolText='5级 (18.9%)' /><set label='6级' value='18.9' toolText='6级 (18.9%)' /><set label='7级' value='18.9' toolText='7级 (18.9%)' /><set label='8级' value='18.9' toolText='8级 (18.9%)' /><set label='9级' value='20.9' toolText='9级 (20.9%)' /><set label='10级' value='18.9' toolText='10级 (18.9%)' /></chart>");
                                    myChart_zhu_1.render("chartdiv_zhu_1");
//横向柱状									
var myChart_bing_1 = new FusionCharts("Bar2D.swf?PBarLoadingText=Loading&XMLLoadingText=Loading&ParsingDataText=Loading", "myChartId_bing_", " 430", "250", "0", "0");
									myChart_bing_1.addParam('wmode','transparent');
                                    myChart_bing_1.setDataXML("<chart baseFontSize='12' numberSuffix='%25' showAboutMenuItem='0' decimals='2' chartTopMargin='0' chartBottomMargin='0' caption='' showValues='0' formatNumberScale='0' bgAlpha='0' logoURL='http://www.baidu.com/more/img/ico_ishouji.gif' logoPosition='TR' startingAngle='60'><set label='1级' value='55.8' displayValue='1级 (55.8%)' toolText='1级 (55.8%)' isSliced='1' /><set label='2级' value='25.3' displayValue='2级 (25.3%)' toolText='2级 (25.3%)'/><set label='3级' value='18.9' displayValue='3级 (18.9%)' toolText='3级 (18.9%)'/><set label='4级' value='18.9' displayValue='4级 (18.9%)' toolText='4级 (18.9%)'/><set label='5级' value='18.9' displayValue='5级 (18.9%)' toolText='5级 (18.9%)'/><set label='6级' value='20.9' displayValue='6级 (20.9%)' toolText='6级 (20.9%)'/><set label='7级' value='10.9' displayValue='7级 (10.9%)' toolText='7级 (10.9%)'/><set label='8级' value='18.9' displayValue='8级 (18.9%)' toolText='8级 (18.9%)'/><set label='9级' value='18.9' displayValue='9级 (18.9%)' toolText='9级 (18.9%)'/><set label='10级' value='30.9' displayValue='10级 (30.9%)' toolText='10级 (30.9%)'/></chart>");
                                    myChart_bing_1.render("chartdiv_bing_1");		
									
